# Generated by Django 3.2.8 on 2021-11-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_alter_reports_user1'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='desc',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
