# Generated by Django 3.2.8 on 2021-11-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_reports_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='em',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
